<a href="https://colab.research.google.com/github/carlos-alves-one/Numpy-Learning/blob/main/Numpy_Learning_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Goldsmiths University of London
**Author....: Carlos Manuel de Oliveira Alves**<br>
**Student..: cdeol003**<br>
**Created..: 23/08/2022**

In [56]:
# import numpy library for linear algebra
import numpy as np

In [57]:
# create an array with function zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
# create an array with function ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
# create an array with function full
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [60]:
# create an array with a list with numbers
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [61]:
# access a specific element in the array
a[2]

3

In [62]:
# replace the value of a specific element in the array
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [63]:
# create an array using the function range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# create an array using the function range but start at a specific number
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [65]:
# create an array using the function linspace
# create an array with 11 elements and with numbers between 0 and 1
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [66]:
# create a multi-dimensional array
# an array with 5 rows and 2 columns
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
# create a multi-dimensional array with a list of numbers
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
# access to an element in a multi-dimensional array
n[0, 1]

2

In [69]:
# replace the value of a specific element in a multi-dimensional array
n[ 0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [70]:
# access the row of a multi-dimensional array
n[0]

array([ 1, 20,  3])

In [71]:
# rewrite the entire row of a multi-dimensional array
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [72]:
# access a specific column in a multi-dimensional array
n[:, 1] # to access the second column

array([20,  5,  1])

In [73]:
# return all the rows of the multi-dimensionl array
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [74]:
# assign new values to a specific columns in multi-dimensionl array
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [75]:
# generate randomly two dimensional array
# the numbers are random between zero and one
# using the seed function to generate the same random numbers
np.random.seed(2)
np.random.rand(5, 2) # 5 rows and 2 columns

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [76]:
# use the standard normal distribution
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [77]:
# generate random numbers between 0 and 100
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [78]:
# generate random integers between 0 and 99
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

**Element-Wise Operations**

In [79]:
# create an array using the arange function
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [80]:
# use element-wise operations addition with array
a + 1

array([1, 2, 3, 4, 5])

In [81]:
# use element-wise operations multiplication with array
a * 2

array([0, 2, 4, 6, 8])

In [82]:
# more complex element-wise operations
b = (10 + (a *2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [83]:
# combine two arrays
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [84]:
# combine two arrays more complex
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

**Comparison Operations**

In [85]:
 a

array([0, 1, 2, 3, 4])

In [86]:
a >= 2

array([False, False,  True,  True,  True])

In [87]:
a > b

array([False, False,  True,  True,  True])

In [88]:
# create an array with elements for which the condition is true
a[a > b]

array([2, 3, 4])

**Summarizing Operations**

In [89]:
a

array([0, 1, 2, 3, 4])

In [90]:
# use the function min that return the smallest number in the array
a.min()

0

In [91]:
# use the function max that return the maximal number in the array
a.max()

4

In [92]:
# use the function sum that computes the sum of all elements in the array
a.sum()

10

In [93]:
# use the function mean that conmputes the average number in tbe array
a.mean()

2.0

In [94]:
# use the standard deviation function
a.std()

1.4142135623730951

In [95]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [96]:
n.sum()

35

In [97]:
n.min()

0

In [98]:
n.max()

20

**Vector Operations**

In [99]:
# create a row vector u
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [100]:
# multiply a numpy array by two
2 * u

array([ 4,  8, 10, 12])

In [101]:
# create a row vector v
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [102]:
# add two row vectors
u + v

array([3, 4, 5, 8])

**Multiplication**

**Vector-vector Multiplication (Dot Product or Inner Product)**

In [103]:
# steps of the multiplication:
# 1. multiply each element of the vector
# 2. sum all the multiplication results
# we can multiply two vectors if they have the same shape
# if we have a row and column vector we need to use the transpose operation
# for one of the vector e.g. if we have a column vector end the other one
# is a row vector we use the transpose operation for this vector
# to convert from row vector to a column vector

In [104]:
# create multi-dimensional array U
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [105]:
# create multi-dimensional array V
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [106]:
# declare a function that does the multiplication of two vectors
def vector_vector_multiplication(u, v):
  
  # first we need to make sure the vectors as the same size
  # use the assert statement known as assertion used to check data
  assert u.shape[0] == v.shape[0]

  # declare variable that store the size of the vector
  n = u.shape[0]

  # declare variable that store the result of the dot product
  result = 0.0

  # declare a loop to visit all elements of the vectors
  for i in range(n):

    # update result with the multiplication of the 2 vectors
    result += u[i] * v[i]

  # declare return the result of the function dot product
  return result

In [107]:
# test the function dot product
vector_vector_multiplication(u, v)

14.0

In [108]:
# numpy has a function does the dot product
u.dot(v)

14